### ISSUE TITLE
Update badges etc. to FINDOLOGIC name space

### ISSUE THREAD

**Issue by georgms** [findologic/findologic-api#37]
The following badges etc. need to be updated:

* Travis CI
* Codeclimate
* Codecov
* Packagist

**Comment by TheKeymaster** [comment]
Reopening this, since step "Packagist" was not done yet.

**Comment by georgms** [comment]
@TheKeymaster I have successfully submitted the package to Packagist but the GitHub webhook fails. Any idea why?

**Comment by TheKeymaster** [comment]
That's weird... are you logged in with the company or with your normal user? Their documentation states

* Make sure [the Packagist application](https://github.com/settings/connections/applications/a059f127e1c09c04aa5a) has access to all the GitHub organizations you need to publish packages from.

**Comment by TheKeymaster** [comment]
As discussed the `README.md` has some errors. Please fix

* the link to travis CI.
* The version, since now it is beta v1.0.0-beta.3, BUT please write v1.0.0-beta.4, because we will create a new release for it.
